[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino, espidf
monitor_speed = 921600
build_flags =
  -std=gnu++17
test_build_src = yes

[env:native]
platform = native
build_flags =
  -std=c++17
build_src_filter =
  +<traffic_parser.cpp>
test_build_src = yes
test_framework = unity
